apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuetest
  namespace: jn-cicd-core
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: carlodockerhub/nodejs-env-test
          resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "200m"
          ports:
            - containerPort: 8080
          envFrom:
          - secretRef:
              name: front-kaxan-secret
          env:
          - name: NODE_ENV
            value: "production"

