metadata:
  labels:
    app: ms-validacion-digital
spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
            - name: LOGGER_LEVEL
              value: INFO
            - name: TZ
              value: "America/Mexico_City"
          envFrom:
            - secretRef:
                name: bsi-informix-estandar-data
            - secretRef:
                name: bsi-informix-digital-data
            - secretRef:
                name: bsi-informix-n2-data
          name: ms-validacion-digital
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 8081
              name: actuator
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 600Mi
            limits:
              cpu: 500m
              memory: 600Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 140
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 140
            periodSeconds: 20
            timeoutSeconds: 10
          volumeMounts:
            - name: application-config
              mountPath: /deployments/config
      nodeSelector:
        node-role.kubernetes.io/compute: "true"
      volumes:
        - name: application-config
          configMap:
            name: cm-ms-bancoppel-n2bcpl
            defaultMode: 420
