apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-validacion-digital
  name: ms-validacion-digital
  namespace: n2bcpl-qa
spec:
  replicas: 1
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8081-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: ms-validacion-digital
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
